name: mikRopML-dev
channels:
  - r
dependencies:
  - r-base=3.6.1
  - r-caret=6.0
  - r-devtools=2.0.2
  - r-docopt=0.6.1
  - r-kernlab=0.8.0
  - r-LiblineaR=2.10
  - r-pkgdown=1.4.1
  - r-pROC=1.14.0
  - r-randomForest=4.6
  - r-rpart=4.1
  - r-testthat=2.1.1
  - r-tictoc=1.0
  - r-tidyverse=1.2.1
  - r-usethis=1.5.0
  - r-xgboost=0.90
  - r-yaml=2.2.0
